### ISSUE TITLE
Getting Net::HTTPServerException when running on an instance with no IAM role

### ISSUE THREAD

**Issue by paulmooring** [poise/citadel#23]
We wrap citadel in a method that catches errors and uses fallback values (for builds and test kitchen).  The new version of Citadel is throwing an error that seems incorrect.  I included the output below but essentially it looks to me like `metadata_service.get('latest/meta-data/iam/security-credentials/')` is expected to return `nil` w/o an IAM role and instead 404s and returns `Net::HTTPServerException`:

```
    amazon-ebs: Net::HTTPServerException
    amazon-ebs: ------------------------
    amazon-ebs: 404 "Not Found"
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /var/chef/cache/cookbooks/citadel/files/halite_gem/citadel.rb:58:in `find_credentials'
    amazon-ebs: /var/chef/cache/cookbooks/citadel/files/halite_gem/citadel.rb:42:in `initialize'
    amazon-ebs: /var/chef/cache/cookbooks/citadel/files/halite_gem/citadel/chef_dsl.rb:26:in `new'
    amazon-ebs: /var/chef/cache/cookbooks/citadel/files/halite_gem/citadel/chef_dsl.rb:26:in `citadel'
    amazon-ebs: /var/chef/cache/cookbooks/chefopslibs/libraries/secrets.rb:12:in `get_secret'
    amazon-ebs: /var/chef/cache/cookbooks/oc-sumologic/recipes/default.rb:10:in `from_file'
    amazon-ebs:
    amazon-ebs: Relevant File Content:
    amazon-ebs: ----------------------
    amazon-ebs: /var/chef/cache/cookbooks/citadel/files/halite_gem/citadel.rb:
    amazon-ebs:
    amazon-ebs: 51:        }
    amazon-ebs: 52:      elsif @node['ec2']
    amazon-ebs: 53:        role_creds = if @node['ec2']['iam'] && @node['ec2']['iam']['security-credentials']
    amazon-ebs: 54:          # Creds loaded from Ohai.
    amazon-ebs: 55:          @node['ec2']['iam']['security-credentials'].values.first
    amazon-ebs: 56:        else
    amazon-ebs: 57:          metadata_service = Chef::HTTP.new('http://169.254.169.254')
    amazon-ebs: 58>>         iam_role = metadata_service.get('latest/meta-data/iam/security-credentials/')
    amazon-ebs: 59:          if iam_role.nil? || iam_role.empty?
    amazon-ebs: 60:            raise 'Unable to find IAM role for node from EC2 metadata'
    amazon-ebs: 61:          else
    amazon-ebs: 62:            creds_json = metadata_service.get("latest/meta-data/iam/security-credentials/#{iam_role}")
    amazon-ebs: 63:            Chef::JSONCompat.parse(creds_json)
    amazon-ebs: 64:          end
    amazon-ebs: 65:        end
    amazon-ebs: 66:        {
    amazon-ebs: 67:          access_key_id: role_creds['AccessKeyId'],
    amazon-ebs:
    amazon-ebs: Platform:
    amazon-ebs: ---------
    amazon-ebs: x86_64-linux
    amazon-ebs:
    amazon-ebs: [2016-06-03T16:30:26+00:00] ERROR: Running exception handlers
    amazon-ebs: [2016-06-03T16:30:26+00:00] ERROR: Exception handlers complete
    amazon-ebs: [2016-06-03T16:30:26+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    amazon-ebs: [2016-06-03T16:30:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    amazon-ebs: [2016-06-03T16:30:26+00:00] ERROR: 404 "Not Found"
```

**Comment by coderanger** [comment]
Should now be correctly raised as CitadelError. The fallback is implemented internally though, if you set the node attributes they will be preferred over metadata fetch.
